baseURL = 'http://xmr.sh'
languageCode = 'en-us'
title = 'xmr.sh'
theme = "Lovelt"
enableGitInfo = true

[menu]
  [[menu.main]]
    weight = 1
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"

   [[menu.main]]
     weight = 6
     identifier = "github"
     pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
     post = ""
     name = ""
     url = "https://github.com/vdo/xmr.sh"
     title = "GitHub"

[params]
  description = "A lighspeed fast Monero node installer."
  defaultTheme = "dark"
  gitRepo = "https://github.com/vdo/xmr.sh"
  [params.header]
    
    [params.header.title]
      logo = "/images/logo-h.png"
      # title name
      # 标题名称
      name = ""
      # you can add extra information before the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # whether to use typeit animation for title name
      # 是否为标题显示打字机动画
      typeit = false
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # URL of avatar shown in home page
      # 主页显示头像的 URL
      avatarURL = ""
      # title shown in home page (HTML format is supported)
      # 主页显示的网站标题 (支持 HTML 格式)
      title = "A Monero kickstarter."
      # subtitle shown in home page (HTML format is supported)
      # 主页显示的网站副标题 (允许 HTML 格式)
      subtitle = "<pre><code>curl -sL get.xmr.sh | sudo bash</code></pre>"
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      # 主页每页显示文章数量
      paginate = 1
  [params.footer]
    enable = false
    # Custom content (HTML format is supported)
    # 自定义内容 (支持 HTML 格式)
    custom = "vdo"
    # whether to show Hugo and theme info
    # 是否显示 Hugo 和主题信息
    hugo = false
    # whether to show copyright info
    # 是否显示版权信息
    copyright = false
